ALTER TABLE do_header
ADD COLUMN IF NOT EXISTS dispatch_date date,
ADD COLUMN IF NOT EXISTS supplier_name varchar(255),
ADD COLUMN IF NOT EXISTS invoice_no varchar(120),
ADD COLUMN IF NOT EXISTS invoice_date date,
ADD COLUMN IF NOT EXISTS model_no varchar(120),
ADD COLUMN IF NOT EXISTS serial_no varchar(120),
ADD COLUMN IF NOT EXISTS material_description text,
ADD COLUMN IF NOT EXISTS date_of_manufacturing date,
ADD COLUMN IF NOT EXISTS basic_price numeric(12, 2),
ADD COLUMN IF NOT EXISTS invoice_qty integer,
ADD COLUMN IF NOT EXISTS dispatched_qty integer,
ADD COLUMN IF NOT EXISTS quantity_difference integer,
ADD COLUMN IF NOT EXISTS no_of_cases integer,
ADD COLUMN IF NOT EXISTS no_of_pallets integer,
ADD COLUMN IF NOT EXISTS weight_kg numeric(12, 3),
ADD COLUMN IF NOT EXISTS handling_type varchar(20),
ADD COLUMN IF NOT EXISTS machine_type varchar(100),
ADD COLUMN IF NOT EXISTS machine_from_time timestamp,
ADD COLUMN IF NOT EXISTS machine_to_time timestamp,
ADD COLUMN IF NOT EXISTS outward_remarks text,
ADD COLUMN IF NOT EXISTS mobile_capture_payload jsonb;
